/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        }
    ],
    "debugbar.queries.explain": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets": [],
    "boost.browser-logs": [],
    "api.excursion.search": [],
    "api.school.excursion.search": [],
    "login": [],
    "logout": [],
    "dashboard": [],
    "info": [],
    "excursion.index": [],
    "excursion.create": [],
    "excursion.wizard": [],
    "excursion.store": [],
    "excursion.edit": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        }
    ],
    "excursion.update": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        }
    ],
    "excursion.destroy": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        }
    ],
    "excursion.files": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        }
    ],
    "excursion.upload-file": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        }
    ],
    "excursion.download-file": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        },
        {
            "name": "filename",
            "required": true
        }
    ],
    "excursion.delete-file": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        },
        {
            "name": "filename",
            "required": true
        }
    ],
    "excursion.submit": [
        {
            "name": "excursion",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.index": [],
    "admin.switch-year": [],
    "admin.session-switch-year": [],
    "admin.select-school": [],
    "admin.clear-school": [],
    "admin.excursions-by-school": [
        {
            "name": "schoolCode",
            "required": true
        }
    ],
    "admin.schools": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
